In [2]:
import numpy as np
import pandas as pd
data = pd.read_csv("training.csv")
data


itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  scurring  skin_peeling  silver_like_dusting  small_dents_in_nails  \
0     ...         0             0                    0                     0   
1     ...         0             0                    0                     0   
2     ...         0             0                    0                     0   
3     ...         0             0                    0                     0   
4     ...         0             0                    0                     0   
...   ...       ...           ...                  ...                   ...   
4915  ...         0             0                    0                     0   
4916  ...         1             0                    0                     0   
4917  ...         0             0                    0                     0   
4918  ...         0             1                    1                     1   
4919  ...         0             0                    0                     0   

      inflammatory_nails  blister  red_sore_around_nose  yellow_crust_ooze  \
0                      0        0                     0                  0   
1                      0        0                     0                  0   
2                      0        0                     0                  0   
3                      0        0                     0                  0   
4                      0        0                     0                  0   
...                  ...      ...                   ...                ...   
4915                   0        0                     0                  0   
4916                   0        0                     0                  0   
4917                   0        0                     0                  0   
4918                   1        0                     0                  0   
4919                   0        1                     1                  1   

                                    prognosis  Unnamed: 133  
0                            Fungal infection           NaN  
1                            Fungal infection           NaN  
2                            Fungal infection           NaN  
3                            Fungal infection 

In [3]:
x = data.iloc[:,:-2].values
y = data['prognosis'].values
x

array([[1, 1, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 1, 1]], dtype=int64)

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 1)
x_train

array([[1, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [5]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
model = dt.fit(x_train,y_train)
model

DecisionTreeClassifier()

In [6]:
y_pred = model.predict(x_test)
y_pred

array(['Urinary tract infection', 'Gastroenteritis', 'Hypothyroidism',
       'Chicken pox', 'Cervical spondylosis', 'Migraine', 'Hepatitis B',
       'Diabetes ', 'Hepatitis E', 'Bronchial Asthma', 'Hyperthyroidism',
       'Cervical spondylosis', 'Migraine',
       '(vertigo) Paroymsal  Positional Vertigo', 'Varicose veins',
       'Dengue', 'Chronic cholestasis', 'Paralysis (brain hemorrhage)',
       'Tuberculosis', 'Hepatitis C', 'Allergy', 'Alcoholic hepatitis',
       'Typhoid', 'Hypertension ', 'Malaria', 'Migraine', 'Jaundice',
       'Cervical spondylosis', 'Dimorphic hemmorhoids(piles)',
       'Hepatitis D', 'Jaundice', 'Cervical spondylosis',
       'Urinary tract infection', 'Heart attack', 'Dengue', 'Hepatitis B',
       'Osteoarthristis', 'Drug Reaction', 'Hypertension ', 'Diabetes ',
       'Drug Reaction', 'Alcoholic hepatitis',
       'Dimorphic hemmorhoids(piles)', 'AIDS', 'Malaria', 'Heart attack',
       'Diabetes ', 'Alcoholic hepatitis', 'Hyperthyroidism',
     

In [7]:
from sklearn import metrics
acc = metrics.accuracy_score(y_test,y_pred)
acc

1.0

In [8]:
datatest = pd.read_csv("testing.csv")
dtst = datatest.iloc[:,:-1].values
resknown = datatest['prognosis'].values
datatest.head()


itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          0                     0                    1          1   
2        0          0                     0                    0          0   
3        1          0                     0                    0          0   
4        1          1                     0                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       1           0             0        0                 0  ...   
2       0           0             1        1                 1  ...   
3       0           0             0        0                 0  ...   
4       0           0             1        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze            prognosis  
0                  0     Fungal infection  
1                  0              Allergy  
2                  0                 GERD  
3                  0  Chronic cholestasis  
4                  0        Drug Reaction  

[5 rows x 133 columns]

In [9]:
result = model.predict(dtst)

result

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo', 'Hepatitis C'],
      dtype=object)

In [10]:
ac = metrics.accuracy_score(result,resknown)
ac


0.9761904761904762

# Using Naiv Bayes Algorithm of supervised learning

In [11]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
data  = pd.read_csv("training.csv")
data.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  scurring  \
0       0           0             0        0                 0  ...         0   
1       0           0             0        0                 0  ...         0   
2       0           0             0        0                 0  ...         0   
3       0           0             0        0                 0  ...         0   
4       0           0             0        0                 0  ...         0   

   skin_peeling  silver_like_dusting  small_dents_in_nails  \
0             0                    0                     0   
1             0                    0                     0   
2             0                    0                     0   
3             0                    0                     0   
4             0                    0                     0   

   inflammatory_nails  blister  red_sore_around_nose  yellow_crust_ooze  \
0                   0        0                     0                  0   
1                   0        0                     0                  0   
2                   0        0                     0                  0   
3                   0        0                     0                  0   
4                   0        0                     0                  0   

          prognosis  Unnamed: 133  
0  Fungal infection           NaN  
1  Fungal infection           NaN  
2  Fungal infection           NaN  
3  Fungal infection           NaN  
4  Fungal infection           NaN  

[5 rows x 134 columns]

In [12]:
x = data.iloc[:,:-2].values
y = data['prognosis'].values

In [13]:
#spliting the test train data
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=35)


In [14]:
from sklearn.preprocessing import StandardScaler
dtc = StandardScaler()
xtrain= dtc.fit_transform(xtrain)
xtest = dtc.transform(xtest)

In [15]:
from sklearn.naive_bayes import GaussianNB
gs = GaussianNB()
model= gs.fit(xtrain,ytrain)
model

GaussianNB()

In [16]:
y_pred = model.predict(xtest)
y_pred

array(['Urinary tract infection', 'Hypothyroidism', 'Hyperthyroidism',
       'Paralysis (brain hemorrhage)', 'Acne', 'Arthritis',
       'Varicose veins', 'Arthritis', 'Allergy', 'Pneumonia',
       'Varicose veins', 'Heart attack', 'Allergy', 'Typhoid', 'AIDS',
       'Chronic cholestasis', 'Peptic ulcer diseae', 'Tuberculosis',
       'Tuberculosis', 'Hypoglycemia', 'Common Cold',
       'Paralysis (brain hemorrhage)', 'Psoriasis', 'Hypothyroidism',
       'Migraine', 'AIDS', 'Diabetes ', 'Drug Reaction',
       'Peptic ulcer diseae', 'Chronic cholestasis',
       'Alcoholic hepatitis', 'Jaundice', 'Hepatitis D', 'Drug Reaction',
       'Migraine', 'Impetigo', 'Bronchial Asthma', 'Varicose veins',
       'Migraine', 'Pneumonia', 'Hepatitis E', 'Hypoglycemia',
       'Dimorphic hemmorhoids(piles)', 'Acne', 'hepatitis A', 'Arthritis',
       'Jaundice', 'Hypertension ', 'Allergy', 'Alcoholic hepatitis',
       'Hepatitis E', 'Dimorphic hemmorhoids(piles)',
       '(vertigo) Paroymsal 

In [17]:
from sklearn import metrics
acc = metrics.accuracy_score(y_pred,ytest)
acc

1.0

In [18]:
#printing the confusion matrics
from sklearn.metrics import confusion_matrix
con = metrics.confusion_matrix(y_pred,ytest)
print(con)


[[21  0  0 ...  0  0  0]
 [ 0 17  0 ...  0  0  0]
 [ 0  0 27 ...  0  0  0]
 ...
 [ 0  0  0 ... 24  0  0]
 [ 0  0  0 ...  0 30  0]
 [ 0  0  0 ...  0  0 18]]


In [19]:
#calculating the accuracy from confusion matrix
a = con.shape
correct_count=0
false_count= 0

for row in range(a[0]):
    for col in range(a[1]):
        if row==col:
            correct_count+=con[row,col]
        else:
            false_count+=con[row,col]
total_count = correct_count+false_count
print("Correct Prediction",correct_count)
print("Wrong Prediction",false_count)
print("Accuracy Score ",correct_count/total_count)

Correct Prediction 984
Wrong Prediction 0
Accuracy Score  1.0


In [20]:
testData= pd.read_csv("testing.csv")
xt = testData.iloc[:,:-1].values
yt = testData['prognosis'].values

testresult= model.predict(xt)
testresult



array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Jaundice',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Typhoid', 'Typhoid', 'Hepatitis D',
       'Hepatitis D', 'Hepatitis C', 'Hepatitis D', 'Hepatitis D',
       'Alcoholic hepatitis', 'Hepatitis D', 'Typhoid',
       'Bronchial Asthma', 'Dimorphic hemmorhoids(piles)', 'Heart attack',
       'Varicose veins', 'Hepatitis D', 'Jaundice', 'Hepatitis D',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo', 'Jaundice'],
      dtype='<U39')

In [21]:
#finding accuracy of the test data
ac = metrics.accuracy_score(yt,testresult)
ac

0.7142857142857143